name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' 

      - name: Restore dependencies
        run: dotnet restore UnitTest/UnitTest.csproj

      - name: Run Unit Tests
        run: dotnet test UnitTest/UnitTest.csproj --logger "trx;LogFileName=test-results.trx" --results-directory UnitTest/TestOutput

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Test Report
          path: UnitTest/TestOutput/test-results.trx
          reporter: dotnet-trx


  performance-tests:
    name: Run Performance Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restors dependencies
        run: dotnet restore PerformanceTest/PerformanceTest.csproj
        
      - name: Run Performance Tests
        run: dotnet run --project PerformanceTest/PerformanceTest.csproj --configuration Release